### ISSUE TITLE
When is a link not a link?

### ISSUE THREAD

**Issue by glynnbird** [cloudant-labs/cloudant-labs.github.io#18]
The confusing thing about the latest UI iteration is "how is the user supposed to get to the actual content". In the search results we have

* the article title - which is an anchor tag linking to the article's URL, but it's behaviour is disabled, so it does nothing (it used to open the modal)
* the article url (grey italic) - which is an anchor tag that works
* a more link - which opens more details thingy

What is the intention here: 

* article title - should this open the "more" section? should it link to the article?
* article url - I think this is ok
* more section - should this have a link to the actual article? If so what should it look like.

**Comment by maston** [comment]
My thoughts:
The article title link seems like where the "click" is going to be to go open the article.  I think that is where I would assume I click.  If it didn't work, I would hit that url.  (if the title is turned into plain text, i am going to click that url if I know that is the link.)
The more section wouldn't have the link because if I know it's the article I want (it's obvious or been there before etc), I don't want to dig.

**Comment by glynnbird** [comment]
@maston good point. So now we have dumped the modal, we can effectively reactive the "article title link" to behave as a link.

**Comment by jessmantaro** [comment]
+1
It should open the article

**Comment by rajrsingh** [comment]
In that case do we really need the grey URL?

**Comment by maston** [comment]
maybe instead of url. you put "article source" (?) 

sent from my bat phone.

**Comment by SoleilPhan** [comment]
+1 it should open the article. It could be that the user wants to just open the article and skip the "more" part. The grey url would show the user where it would take them (i.e., github) which would supplement the user's decision to open the link or not.

**Comment by glynnbird** [comment]
Which is what Google does:
* document title in Blue
* URL underneath in green (not clickable, I might add)
